#! /bin/sh

nitrogen --restore &
eww daemon &
eww open-many bar workspaces menu date &
picom -f &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#fc5d7c"
bspc config presel_feedback_color "#fc5d7c"

#bspc rule -r "*"
#bspc rule -a eww --layer below
#bspc rule -a eww layer=below

xsetroot -cursor_name left_ptr
setxkbmap us -variant intl
