#! /bin/bash

desktop=$(xprop -root _NET_CURRENT_DESKTOP)

if [[ ${desktop: -1} == 1 ]]; then
	echo ""

elif [[ ${desktop: -1} == 2 ]]; then
	echo ""

elif [[ ${desktop: -1} == 3 ]]; then
	echo ""

elif [[ ${desktop: -1} == 4 ]]; then
	echo ""

else [[ ${desktop: -1} == 5 ]];
	echo ""

fi

desktop=${desktop: -1}

echo $desktop
